### Stage 1 scoring components
[[component]]
[component.HBondDonors]

[[component.HBondDonors.endpoint]]
name = "HBond Donors"  # user chosen name for output
weight = 0.5  # weight to fine-tune the relevance of this component


[[component]]
[component.HBondAcceptors]

[[component.HBondAcceptors.endpoint]]
name = "HBond Acceptors"  # user chosen name for output
weight = 0.5  # weight to fine-tune the relevance of this component

