### Stage 2 scoring components
[[component]] 
[component.QED] # This is the specific scoring function to be used

[[component.QED.endpoint]]
# weight = 0.5  # weight to fine-tune the relevance of this component
name = "QED Score" # user chosen name for output 
