### Stage 2 scoring components
[[component]] 
[component.numsp] # This is the specific scoring function to be used

[[component.numsp.endpoint]]
# weight = 0.5  # weight to fine-tune the relevance of this component
name = "numsp Score" # user chosen name for output 
